spring:
  config:
    activate:
      on-profile: local

  application:
    name: LogisticProject

  security:
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      idle-timeout: '30000'
      maximum-pool-size: '10'
      connection-timeout: '20000'
      pool-name: HikariCP
      max-lifetime: '1800000'
      minimum-idle: '5'
    username: postgres
    password: 2365
    url: jdbc:postgresql://localhost:5432/logistic

  liquibase:
    enabled: false
    default-schema: public
    change-log: classpath:/db/changelog-master.xml

  sql:
    init:
      platform: postgres

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: 'false'
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        enable_lazy_load_no_trans: true

  data:
    redis:
      host: localhost
      port: 6379


      caching:
        auto-delete-time-at-minute: 1

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 1000MB
      enabled: true

scheduling:
  tasks:
    auto-clear-false-attachment-with-checking-from-caching-on-minute: 1

server:
  port: 8081

file:
  saving:
    default-directory:
    #              is-enabled: true

    base-directory:
      path: D:\Projects\resource\logistic\photos
      if-dont-exist-the-directory-create: true
      if-cannot-access-the-directory-use-default-directory: true

springdoc:
  swagger-ui:
    path: /swagger
