spring:
  config:
    activate:
      on-profile: dev

  application:
    name: LogisticProject

  security:
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/logistic

  liquibase:
    change-log: db/changelog/changelogMaster.xml

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  data:
    redis:
      host: redis-10089.c292.ap-southeast-1-1.ec2.redns.redis-cloud.com
      port: 10089
      username: default
      password: TXzv3SVINsKslylW624NmktBl5F6sqfQ
      caching:
        auto-delete-time-at-minute: 1

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
      enabled: true

scheduling:
  tasks:
    auto-clear-false-attachment-with-checking-from-caching-on-minute: 1


server:
  port: 8081

file:
  saving:
    default-directory:
      is-enabled: true

    base-directory:
      path: D:\Projects\resource\logistic\photos
      if-dont-exist-the-directory-create: true
      if-cannot-access-the-directory-use-default-directory: true

