insert into public.region (name_en)
values  ('Yangiaryk'),
        ('Yangibozor'),
        ('Urganch'),
        ('Qarshi'),
        ('Turkman'),
        ('Moskva'),
        ('Quqan'),
        ('Istanbul'),
        ('Ashhabad'),
        ('Termiz'),
        ('Namangan'),
        ('Andijon'),
        ('Astana'),
        ('Tehron'),
        ('Bagdad'),
        ('Islamabad'),
        ('Pekin'),
        ('Ulan Batar'),
        ('Tokio');