insert into public.region (id, name_en)
values  (1, 'Yangiaryk'),
        (2, 'Yangibozor'),
        (3, 'Urganch'),
        (4, 'Qarshi'),
        (5, 'Turkman'),
        (6, 'Moskva'),
        (7, 'Quqan'),
        (8, 'Istanbul'),
        (9, 'Ashhabad'),
        (10, 'Termiz'),
        (11, 'Namangan'),
        (12, 'Andijon'),
        (13, 'Astana'),
        (14, 'Tehron'),
        (15, 'Bagdad'),
        (16, 'Islamabad'),
        (17, 'Pekin'),
        (18, 'Ulan Batar'),
        (19, 'Tokio');